config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'


  root 'main#home'
  get '/about', to: 'main#about'

  resources :articles
  resources :categories, except:[:destroy]

  get 'signup', to: 'users#new'
  # post 'users', to: 'users#create'
  resources :users, exept: [:new]
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 3 }
  validates :user_id, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: {maximum: 10, minimum: 3}
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  
  has_many :articles
  before_save { self.email = email.downcase }
  validates :username, presence: true, length: { minimum: 3, maximum: 25 }, uniqueness: true
  validates :email, presence: true, length: { minimum: 3, maximum: 100 }, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP } 
  has_secure_password
  gravtastic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def logged_in? 
    !current_user.nil?
  end

  def authentication_required
    redirect_to login_path if !logged_in?
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end

  def current_user?(user)
    user == current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = 'You must be logged in to perform this action'
      redirect_to root_path
    end
  end

  helper_method :current_user, :logged_in?, :current_user?, :require_user
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :findArticle, only: [:show, :edit, :update, :destroy]
  before_action :require_user, expect:[:index, :show] 
  before_action :require_same_user, only:[:edit, :update, :destroy] 

  def index
    @articles = Article.paginate(page: params[:page], per_page: 4)
  end

  def new 
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = 'Article was created'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:success] ='Article was updated'
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy 
    @article.destroy
    redirect_to articles_path
  end

  private
  def findArticle
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    if current_user != @article.user
      flash[:danger] = 'You can only delete your own articles'
      redirect_to root_path
    end
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index

  end

  def new

  end

  def show

  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end
  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email:params[:session][:email].downcase)
   if user && user.authenticate(params[:session][:password])
    session[:user_id] = user.id
    flash[:success] = 'You have succesfully loged in'  
    redirect_to user_url(user)
   else 
    flash.now[:danger] = 'Something was wrong '  
    render 'new'   
   end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have loged out'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only:[:edit, :update] 

  

  def index 
    @users = User.paginate(page: params[:page], per_page: 4)
  end

  def new
    @user = User.new
  end

  def create 
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'Welcome to the blog'
      redirect_to login_path 
    else 
      render :new
    end
  end

  def edit
    
  end

  def update

    if @user.update(user_params)
      flash[:success] = 'Your account was updated'
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show

    @user_articles = @user.articles.paginate(page: params[:page], per_page: 4)
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:danger] = 'You can only edit your own account'
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # # helper_method :all

  # def current_user
  #   @current_user ||= User.find(session[:user_id]) if session(:user_id)
  # end

  # def logged_in?
  #   !!current_user

  # end

  # def require_user
  #   if !logged_in?
  #     flash[:danger] = 'You mush be loged in'
  #     redirect_to root_path

  #   end

  # end

end

app/views/articles/_article.html.erb
<% obj.each do |article|%>
<div>
  <div class="col-sm-8 m-auto" >
    <div class="well well-lg mb-2" >

    <div class = "article-title pb-2" >
       <%= link_to article.title,  article_path(article) %>
    </div>

    <div class="d-flex">
      <p class="m-0 text-bold"> Created by: <%= article.user.username if article.user %>, </p>
      <p  class="m-0">  at: <%= time_ago_in_words(article.created_at) %></p>
    </div>
    
    <div class = "article-body pb-2" >
      <%= truncate(article.description, length: 100)%>
    </div>

    <% if logged_in? && current_user == article.user %>
      <div class='article-actions pt-3 d-flex'>
        <%= link_to 'Edit this article', edit_article_url(article), class: 'btn btn-xs btn-primary' %> 
        <%= button_to 'Delete this article', article_path(article), method: :delete, 
                                          data: {confirm: 'Are you sure that you want to delete this article?'},
                                          class: 'btn btn-xs btn-danger mx-2' %> 
      </div>
    <% end %>

    </div>
  </div>
</div>
<% end %>

app/views/articles/_form.html.erb
<% if  @article.errors.any?  %>
<%= render 'shared/errors', obj: @article%>
<% end %>


      <div class="row form">
        <%= form_for @article do |f| %>
      <div class= "form-group" >
        <%= f.label "Title:", class: "col-sm-2 col-form-label text-end" %> 
        <div class = "col-sm-8" >
        <%= f.text_field :title,   class:"form-control", placeholder: "Title of the article", autofocus: true %>
        </div>
      </div>

      <div class= "form-group" >
        <%= f.label "Description:", class: "col-sm-2 col-form-label text-end" %> 
        <div class = "col-sm-8" >
        <%= f.text_area :description, rows: 8,   class:"form-control", placeholder: "Description of the article", autofocus: true %>
        </div>
      </div>

      <div class= "form-group" >
      <div class= "col-sm-2">
      </div>
            <%= f.submit class: "btn btn-lg btn-warning submit-btn " %>
      </div>
    <% end %>
    <div class = " col-xs-4 col-xs-offset-4"> 
    </div>
</div>

 

app/views/articles/edit.html.erb
<h1 class = "form-h1">Edit article with id: <%= params[:id] %> </h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center p-4" >Listing all articles</h1>
<div class='d-flex justify-content-center'>

    <%= will_paginate(@articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer)%>
</div>
<%= render 'article', obj: @articles %>

<div class='d-flex justify-content-center'>
 <%= will_paginate(@articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer)%>
</div>

app/views/articles/new.html.erb
<h1 class = "form-h1 text-center"> Create a new article </h1>
<%
=begin%>
 <%= turbo_frame_tag "articles" do %>
  <%= render 'form' %>
<%end%> 
<%
=end%>

  <%= render 'form' %>

app/views/articles/show.html.erb
<h2 class = "form-h1 text-center pb-2">Title: <%= @article.title%> <%= params[:id] %></h2>

<div class="well col-sm-8 d-flex justify-content-center flex-column align-content-center" >  


  <div class='row d-flex justify-content-center flex-column align-items-center'>
  <div class= 'col-md-3 mt-2 text-center'> 
    <small>Created by: </small>
    <div class='text-center'><%= image_tag @article.user.gravatar_url(:rating => 'R', :secure => true), class: 'rounded' %> </div>
     <div class= "mt-2"> <%= link_to @article.user.username, user_path(@article.user) %></div>
    <div class= "mt-2"> <%= pluralize(@article.user.articles.count, 'article') if @article.user.articles.any? %> </div>
   </div>
</div>
  <h4 class='text-center'> Description: </h4>
  <hr> 
  <div > 
    <p> <%= @article.description%> </p>
  </div> 

  <hr> 

    <% if logged_in? && current_user == @article.user %>
    <div class='article-actions d-flex'>
      <%= link_to 'Edit this article', edit_article_url(@article), class: 'btn btn-xs btn-primary' %> 
      <%= button_to 'Delete this article', article_path(@article), method: :delete, 
                                        data: {confirm: 'Are you sure that you want to delete this article?'},
                                        class: 'btn btn-xs btn-danger mx-2' %> 
      <%= link_to 'See all articles', articles_url, class: 'btn btn-xs btn-success' %> 
    </div>
  <% end %>

</div>

app/views/layouts/_footer.html.erb
  <footer class= "bg-dark" >
    <small class="text-white">
      Copyright &copy; 
    <small>
  </footer>

app/views/layouts/_messages.html.erb
    <div class="row d-flex justify-content-center" >
      <div class="col-sm-8" >

          <% flash.each do |name, msg|%>
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
              <%= content_tag :div, msg, :id =>  "flash_#{name}" if msg.is_a?(String)%>
               <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div >
          <% end %>

      </div>
    </div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">

     <%= link_to "The Blog", root_path, id: 'logo', class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="navbar-nav justify-content-between me-auto mb-2 mb-lg-0 px-4" style="width: 100%;">
      <% if logged_in? %>
        <div class="d-flex">
          <li> <%= link_to 'Home', root_path, class: 'nav-link' %></li> 
          <li> <%= link_to 'All articles', articles_path, class: 'nav-link' %></li>
          <li> <%= link_to 'All users', users_path, class:  'nav-link' %></li>
          <li> <%= link_to 'New article', new_article_path, class:  'nav-link' %></li>
          <li> <%= link_to 'My articles', user_path(current_user), class:  'nav-link' %></li>
        </div>
          <div class="d-flex">
            <li> <%= link_to 'Logout', logout_path, method: :delete, class:  'nav-link' %></li>
            <li> <%= link_to 'Edit account', edit_user_path(current_user), class:  'nav-link' %></li>
          </div>

        <% else %>
         <div class="d-flex  justify-content-between" style="width: 100%;">
          <li> <%= link_to 'Home', root_path, class: 'nav-link' %></li> 
          <div class="d-flex ">
          <li> <%= link_to 'Log in', login_path, class:  'nav-link' %></li>
          <li> <%= link_to 'Sign up', signup_path, class:  'nav-link' %></li>
          <div>
         </div>
        <% end %>
      </div>
      
      
<%
=begin%>
 
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>

      <div class="dropdown show">
        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown link
        </a>

        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </div> 
<%
=end%>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogUdemy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class= "pb-5  ">
  <%= render 'layouts/navbar' %>

  <% if flash.any? %>
    <%= render 'layouts/messages' %>
  <% end %>

  <div>
    <%= yield %>
  </div>
       <%= render 'layouts/footer' %>
      <%
=begin%>
 <%= debug(params) if Rails.env.development? %> 
<%
=end%>
      
  </body>
</html>

app/views/main/about.html.erb
<h1 class="text-center p-2"> Rails Blog </h1>

app/views/main/home.html.erb
<div class= "jumbotron">
  <h1  class="text-lg mt-5 fs-1" >The Blog </h1>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-warning btn-lg mb-4  " %>
</div>

app/views/shared/_errors.html.erb
<div class="row d-flex justify-content-center p-3" >
  <div class="col-sm-8" >
    <div class="custom-card" >
      <div class="custom-card-title" >
      <h2>
      <%= pluralize(obj.errors.count, 'error' )%>
      prohibited article from being saved:
      </h2>

      <div class="custom-card-body">
        <ul> 
          <% obj.errors.full_messages.each do |msg| %>  
            <li><%= msg%></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
      <div class= "form-group" >
        <%= f.label "Username:", class: "col-sm-2 col-form-label text-end" %> 
          <div class = "col-sm-8" >
          <%= f.text_field :username,   class:"form-control", Username: "Title of the article", autofocus: true %>
        </div>
      </div>

      <div class= "form-group" >
        <%= f.label "Email:", class: "col-sm-2 col-form-label text-end" %> 
        <div class = "col-sm-8" >
        <%= f.email_field :email, class:"form-control", placeholder: "Email", autofocus: true %>
        </div>
      </div>

      <div class= "form-group" >
        <%= f.label "Password:", class: "col-sm-2 col-form-label text-end" %> 
        <div class = "col-sm-8" >
        <%= f.password_field :password, class:"form-control", placeholder: "Password", autofocus: true %>
        </div>
      </div>

      <div class= "form-group" >
        <div class= "col-sm-2"></div>
        <%= f.submit 'Submit', class: "btn btn-lg btn-warning submit-btn " %>
      </div>
            
  <% end %>

app/views/users/edit.html.erb
<h1 class = "text-center">Edit your account</h1>

<div class="row form">
  <%= render "form" %>


</div>

 

app/views/users/index.html.erb
<h1 class = 'text-center m-4'>All bloggers</h1>

<% @users.each do |user| %>
<div class='row d-flex justify-content-center flex-column align-items-center'>
  <div class= 'col-md-3 mt-2 bg-secondary-custom text-center'> 
    <div class='text-center'><%= image_tag user.gravatar_url(:rating => 'R', :secure => true), class: 'rounded' %> </div>
     <div class= "mt-2"> <%= link_to user.username, user_path(user) %></div>
    <div class= "mt-2"> <%= pluralize(user.articles.count, 'article') if user.articles.any? %> </div>
   </div>
</div>
<% end %>
<div class='d-flex justify-content-center mt-4  '>
 <%= will_paginate(@articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer)%>
</div>

app/views/users/new.html.erb
<h1 class = 'text-center'>Sign up for Blog</h1>
<div class="row form">
  <%= render "form"%>
</div>

 

app/views/users/show.html.erb
<h1 class="text-center"> Welcome <%= @user.username %> </h1>
<div class='row d-flex justify-content-center flex-column align-items-center'>
  <div class= 'col-md-4 text-center'> <%= image_tag @user.gravatar_url(:rating => 'R', :secure => true) %> </div>
  <div class='text-center'> <%= @user.username %>'s articles</div>

   <h3 class= "text-center my-4"> <%= 'You have no articles yet! ' if !@user.articles.any? %> </h3>
  <div class='d-flex justify-content-center mt-4  '>
   <%= will_paginate(@user_articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer)%>
  </div>

  <%= render 'articles/article', obj: @user_articles %>
    <div class='d-flex justify-content-center mt-4  '>
   <%= will_paginate(@user_articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer)%>
</div>
</div>